openapi: 3.0.0
info:
  title: API de Pedidos
  description: Documentação da API de Pedidos
  version: 1.0.0

paths:
  /orders:
    post:
      summary: Cria um novo pedido
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderDto'
      responses:
        '201':
          description: O pedido foi criado com sucesso
        '400':
          description: Dados inválidos.
        '500':
          description: Erro interno do servidor.

components:
  schemas:
    AdditionDto:
      type: object
      properties:
        additionId:
          type: string
        price:
          type: number
    ProductDto:
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: number
        additions:
          type: array
          items:
            $ref: '#/components/schemas/AdditionDto'
    CreateOrderDto:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
        address:
          type: string
        paymentMethod:
          type: string
        name:
          type: string
        phone:
          type: string
        status:
          type: string
          enum: [PENDENTE, PREPARANDO, ENVIADO, CANCELADO]
        changeFor:
          type: number
        deliveryMethod:
          type: string
        neighborhoodId:
          type: string
